### ISSUE TITLE
deposit-ui: removing ORCID on record edit not possible

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1385]
Steps to reproduce:

1. Create minimal record including author with ORCID
1. "Edit" record, remove author's ORCID and "Save"
1. `Validation error. Authors: Not a valid ORCID identifier`

A way to circumvent/fix the issue is to remove the entire author entry (with the "x" button) and re-enter the name and affiliation, though for a regular user this is not obvious.

**Comment by Zimmi48** [comment]
This issue made me lose about one hour to understand it, find the work around and apply it, while updating a Zenodo entry with many contributors. Between two versions of the software, the list of contributors had changed. I did the mistake of reusing former contributor entries with an ORCID to replace them by new contributors without an ORCID, thus triggering the error. The validation error message is very misleading and at the very least the message should be fixed.

There is another related bug that made applying the workaround even harder which is that if you already got the validation error, and you delete the author but you already have another author below with no ORCID, the validation error is moved to the next author and prevents you from saving again!

The two bugs apply both to the author fields and the contributor fields.

**Comment by raymondben** [comment]
Can confirm that this bug still exists. Further, if you delete the author with the "invalid" (empty) ORCID, the validation error moves to the next author *even if they have a valid ORCID*, which then has to be edited to re-trigger the validation.

**Comment by ssmithClimate** [comment]
This issue still exists

**Comment by Zimmi48** [comment]
Yes, and since I need to publish a new version of our Zenodo record about every six months, I again suffered from this just two days ago.

**Comment by Danapit** [comment]
This is really a very frustrating bug, which prevents saving a record, especially when it follows an addition of a long list of authors.
